[connections.supabase_db]
dialect = "postgresql"
host = "aws-1-sa-east-1.pooler.supabase.com"
port = 6543
database = "postgres"
username = "postgres.vrvaebkzczdaeeuhffof"
password = "lKd1PY9nI1EyF7af"
[email_credentials]
sender_email = "brian_fachini@estudante.sesisenai.org.br"
sender_password = "ggvg yqwj puni houk"
