# .streamlit/secrets.toml

[connections.supabase_db]
dialect = "postgresql"
host = "db.vrvaebkzczdaeeuhffof.supabase.co"
port = 5432
database = "postgres"
username = "postgres"
password = "COLOQUE_AQUI_A_SENHA_QUE_VOCÊ_ANOTOU_QUANDO_CRIOU_O_PROJETO"
