# .streamlit/secrets.toml

[connections.supabase_db]
dialect = "postgresql"
host = "db.vrvaebkzczdaeeuhffof.supabase.co"
port = 5432
database = "postgres"
username = "postgres"
password = "yDk82xKhMy5CIZND"
