[connections.supabase_db]
dialect = "postgresql"
host = "aws-1-sa-east-1.pooler.supabase.com"
port = 6543
database = "postgres"
username = "postgres.vrvaebkzczdaeeuhffof"
password = "COLOQUE_SUA_SENHA_REAL_AQUI"

[email_credentials]
sender_email = "brian_fachini@estudante.sesisenai.org.br"
sender_password = "sua_senha_de_app_de_16_letras_aqui"
